#!/usr/bin/env ruby
$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require 'my_menu'

## Create new blank menu
## allows for easy output to terminal
my_menu = MyMenu::Menu.new(STDOUT)
## Welcome message and prompt for data file
data_file = gets.chomp

## Returns an instance of MenuUtil
menu_util = my_menu.parse_data_file(data_file)

my_menu.run

at_exit { puts "\n***\nThanks for dinning with us please come again\n***" }

## Allow for multipule menus to be added one after the other
# while data_file = gets.chomp
#   menu, total = parse_data_file
#   my_menu.read_menu(menu, total)
#   my_menu.suggest_items
# end
