#!/usr/bin/env ruby
$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require 'my_menu'

## Create new blank menu
## allows for easy output to terminal
my_menu = MyMenu::Menu.new(STDOUT)
## Welcome message and prompt for data file
my_menu.greeting
data_file = gets.chomp
# my_menu.ordering_instructions

## Returns an instance of FileResource
file_resource = my_menu.parse_data_file(data_file)
## prepare file to be sent to the menu
## TODO if menu is empty Hash than exit program there are no
## available items to order
total, menu = file_resource.assemble_menu

## Returns menu items that meet the total or a message that no items are available
my_menu.suggest_items(menu, total) # was in vars passed dish_max_ordered


at_exit { puts "\n***\nThanks for dinning with us please come again\n***" }

## Allow for multipule menus to be added one after the other
# while data_file = gets.chomp
#   menu, total = parse_data_file
#   my_menu.read_menu(menu, total)
#   my_menu.suggest_items
# end
